### ISSUE TITLE
Datalogic SDK 1.7.21 works on Joya Touch, but not on DL-Axist

### ISSUE THREAD

**Issue by AdelSari** [datalogic/android-sdk-addon#2]
Hi,
i am testing the SDK within my Android application on the Joya Touch (Android 6) and it works fine,
When i switch to DL-Axist (Android 4.4), the application crash, the minSDK is set to Api 19,
i am using datalogic-sdk-v1.7-21
can you help please,
thanks

**Comment by guidodavide** [comment]
1. First of all, be sure to not use specific functionalities of newer SDK (1.7) in your current Axist image (containing SDK 1.4).
Otherwise, the usage of new features will lead to a crash.
2. Do you have a log file? Be sure that the issue is not related to the Datalogic SDK
3. For firmware updates please contact your technical support of reference or visit:
[Axist support page](http://www.datalogic.com/eng/products/healthcare-transportation-logistics-retail/mobile-computers/dl-axist-pd-702.html#download) section _Software & Utilities_
We are going to release a new software release for Axist with latest Datalogic SDK.

**Comment by AdelSari** [comment]
Thanks guidodavide, it's working now,
i have excluded the datalogic.jar library in the app module, like that the app uses the embeded 1.4 SDK.

thanks a lot.
